In [1]:
!pip install numpy

In [2]:
conda install numpy

^C

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
lst1= [1,2,3]
lst2 = [4,5,6]
arr=np.array([lst1,lst2])
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
arr.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [7]:
arr= np.arange(0,20,step=2)

In [8]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [10]:
#copy function and broadcasting

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
#binding of C++ libary = Numpy
 

In [1]:
import numpy as np

In [7]:
my_lst=[1,2,3,4]
arr= np.array(my_lst)

In [8]:
type(arr)

numpy.ndarray

In [9]:
#.shap is used to define the shape of an array

In [10]:
arr.shape

(4,)

In [11]:
#2d array 
#2 brackets open 2 brackets closed

In [12]:
array=([[1,2,3,4,5],[2,3,4,5,6],[9,7,6,8,9]])

In [17]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [18]:
## some conditions very useful in exploratory data analysis

In [19]:
val = 2
arr< 2

array([ True, False, False, False])

In [20]:
arr*2

array([2, 4, 6, 8])

In [21]:
import seaborn as sns
import pandas as pd